Repository CS2103-AY1819S1-F11-4/main, pull requests merged in 2018-11, with the labels that each got.

#151 resolve #150
  .gitignore
  docs/UserGuide.adoc
  src/META-INF/MANIFEST.MF
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/CreateCommand.java
  src/main/java/seedu/address/logic/commands/LoginCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CreateCommandParser.java
  src/main/java/seedu/address/logic/parser/LoginCommandParser.java
  src/main/java/seedu/address/logic/security/Encrypt.java
  src/main/java/seedu/address/model/accounts/Accounts.java
  src/main/java/seedu/address/storage/UserAccountStorage.java
  src/main/resources/META-INF/MANIFEST.MF
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CreateCommandTest.java
  src/test/java/seedu/address/logic/commands/LoginCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/ui/CommandBoxTest.java
  src/test/java/systemtests/AddCommandSystemTest.java
  src/test/java/systemtests/ClearCommandSystemTest.java
  src/test/java/systemtests/DeleteCommandSystemTest.java
  src/test/java/systemtests/EditCommandSystemTest.java
  src/test/java/systemtests/FindCommandSystemTest.java
  src/test/java/systemtests/SelectCommandSystemTest.java
Labels: AwaitingReview.ReadyForMerge, feature.Security

#153 Timeslot method still not fixed, rename methods, remove bugs
  docs/UserGuide.adoc
  src/main/java/seedu/address/logic/commands/AddTimetableCommand.java
  src/main/java/seedu/address/logic/commands/DeleteTimetableCommand.java
  src/main/java/seedu/address/logic/commands/DownloadTimetableCommand.java
  src/main/java/seedu/address/logic/commands/EditTimetableCommand.java
  src/main/java/seedu/address/logic/commands/ViewGroupAllAvailableTimeslotCommand.java
  src/main/java/seedu/address/logic/commands/ViewGroupRankedAvailableTimeslotCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ViewGroupAllAvailableTimeslotCommandParser.java
  src/main/java/seedu/address/logic/parser/ViewGroupRankedAvailableTimeslotCommandParser.java
  src/main/java/seedu/address/model/group/Group.java
  src/main/java/seedu/address/model/person/timetable/TimetableData.java
Labels: AwaitingReview.ReadyForMerge, feature.Timeslot

#155 V1.3 Removed specific FindCommand & BugFix
  README.adoc
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  src/main/java/seedu/address/logic/commands/FindAddressCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/FindEmailCommand.java
  src/main/java/seedu/address/logic/commands/FindNameCommand.java
  src/main/java/seedu/address/logic/commands/FindPhoneCommand.java
  src/main/java/seedu/address/logic/commands/FindTagCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/FindAddressCommandParser.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/logic/parser/FindEmailCommandParser.java
  src/main/java/seedu/address/logic/parser/FindNameCommandParser.java
  src/main/java/seedu/address/logic/parser/FindPhoneCommandParser.java
  src/main/java/seedu/address/logic/parser/FindTagCommandParser.java
  src/main/java/seedu/address/model/person/NameContainsKeywordsPredicate.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
  src/test/java/systemtests/FindCommandSystemTest.java
Labels: AwaitingReview.ReadyForMerge, feature.Friends

#156 Ttv1.3
  src/main/java/seedu/address/logic/commands/AddTimetableCommand.java
  src/main/java/seedu/address/logic/commands/DeleteTimetableCommand.java
  src/main/java/seedu/address/logic/commands/DownloadTimetableCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/EditTimetableCommand.java
  src/test/java/seedu/address/logic/commands/DownloadTimetableCommandTest.java
Labels: AwaitingReview.ReadyForMerge, feature.Timetable

#158 v1.3 Time slot methods
  src/main/java/seedu/address/model/group/Group.java
Labels: AwaitingReview.ReadyForMerge, feature.Timeslot

#160 V1.3 timeslot
  src/main/java/seedu/address/model/group/Group.java
Labels: AwaitingReview.ReadyForMerge, feature.Timeslot

#198 FindCommand & AddCommand Update
  src/main/java/seedu/address/commons/util/StringUtil.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/model/person/Address.java
  src/main/java/seedu/address/model/person/Email.java
  src/main/java/seedu/address/model/person/NameContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/Phone.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
  src/test/java/systemtests/AddCommandSystemTest.java
Labels: AwaitingReview.ReadyForMerge, feature.Friends

#195 This commit resolves issue #192,188,186,184,179,182,
  docs/UserGuide.adoc
  docs/images/add_timetable_fl.png
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/DeleteTimetableCommand.java
  src/main/java/seedu/address/logic/commands/DownloadTimetableCommand.java
  src/main/java/seedu/address/logic/commands/EditTimetableCommand.java
  src/main/java/seedu/address/logic/parser/AddTimetableCommandParser.java
  src/main/java/seedu/address/logic/parser/ArgumentMultimap.java
  src/main/java/seedu/address/logic/parser/EditTimetableCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/test/java/seedu/address/logic/commands/DownloadTimetableCommandTest.java
  src/test/java/seedu/address/logic/parser/AddTimetableCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditTimetableCommandParserTest.java
Labels: WIP.NotReadyForMerge, feature.Timetable, type.Bug

#209 allow read-only commands before login
  docs/UserGuide.adoc
  docs/team/aspiringdevslog.adoc
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
Labels: WIP.NotReadyForMerge

#213 Update Diagrams of Logic, Highlevelsequence and Add GroupPersonClassDiagrams
  docs/DeveloperGuide.adoc
  docs/diagrams/GroupPersonInteractionClassesOOPDiagram.pptx
  docs/diagrams/HighLevelSequenceDiagrams.pptx
  docs/diagrams/LogicComponentClassDiagram.pptx
  docs/diagrams/LogicComponentUpdatedSequenceDiagram.pptx
  docs/images/GroupPersonClassDiagram.png
  docs/team/happytreat.adoc
  src/main/java/seedu/address/logic/commands/ViewGroupRankedAvailableTimeslotCommand.java
  src/main/java/seedu/address/model/group/Group.java
Labels: AwaitingReview.ReadyForMerge, feature.Friends, feature.Groups

#214 timetable and portfolio
  docs/UserGuide.adoc
  docs/team/souless94.adoc
  src/main/java/seedu/address/logic/commands/AddTimetableCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/timetable/Timetable.java
  src/main/java/seedu/address/model/person/timetable/TimetableData.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/person/timetable/TimetableDataTest.java
Labels: AwaitingReview.ReadyForMerge, feature.Timetable

#215 update docs + fix bugs
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/images/LoginCommandSequenceDiagram.png
  docs/images/SecurityMechanismActivityDiagram.png
  docs/team/aspiringdevslog.adoc
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/commands/CreateCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/storage/UserAccountStorage.java
  src/test/java/seedu/address/logic/commands/CreateCommandTest.java
  src/test/java/systemtests/AddCommandSystemTest.java
  src/test/java/systemtests/ClearCommandSystemTest.java
  src/test/java/systemtests/DeleteCommandSystemTest.java
  src/test/java/systemtests/EditCommandSystemTest.java
  src/test/java/systemtests/FindCommandSystemTest.java
  src/test/java/systemtests/HelpCommandSystemTest.java
  src/test/java/systemtests/SelectCommandSystemTest.java
Labels: AwaitingReview.ReadyForMerge

#217 Edit DeleteGroupCommand SD
  docs/UserGuide.adoc
  docs/diagrams/DeleteGroupCommandSD.pptx
  docs/images/DeleteGroupCommandLogicSD.png
  docs/images/DeleteGroupCommandModelSD.png
Labels: AwaitingReview.ReadyForMerge, feature.Groups

#218 update tags
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/team/aspiringdevslog.adoc
Labels: AwaitingReview.ReadyForMerge, feature.Security

#219 update tags
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/team/aspiringdevslog.adoc
Labels: AwaitingReview.ReadyForMerge, feature.Security

#221 DeveloperGuide: Update Add/Find Command UML
  docs/DeveloperGuide.adoc
  docs/images/FindSequence1.png
Labels: WIP.NotReadyForMerge, feature.Friends

#224 DeveloperGuide: Update ActivityDiagram for FindCommand
  docs/DeveloperGuide.adoc
  docs/images/FindActivity.png
  docs/images/FindFeature1.png
  docs/images/FindSequence.png
Labels: feature.Friends

#226 fix typo in timetable sequence diagram and fix bug
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/images/addtimetablediagram.png
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/AddTimetableCommand.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/timetable/TimetableData.java
  src/test/java/seedu/address/logic/commands/AddTimetableCommandTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
Labels: AwaitingReview.ReadyForMerge, feature.Timetable

#229 minor fixes
  docs/DeveloperGuide.adoc
  src/main/java/seedu/address/model/person/timetable/TimetableData.java
Labels: AwaitingReview.ReadyForMerge, feature.Timetable

#230 minor fixes
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  src/main/java/seedu/address/model/person/timetable/TimetableData.java
  src/test/java/seedu/address/model/person/timetable/TimetableDataTest.java
Labels: AwaitingReview.ReadyForMerge, feature.Timetable, type.Bug

#233 update DG, UG and samples
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/images/addTimetable-step-2.png
  docs/images/timetableclassdiagram.png
  src/main/java/seedu/address/model/util/SampleDataUtil.java
Labels: AwaitingReview.ReadyForMerge, feature.Timetable

#243 update PPP
  docs/UserGuide.adoc
  docs/images/Ui.png
  docs/team/souless94.adoc
  src/main/java/seedu/address/commons/core/Config.java
  src/test/java/seedu/address/commons/core/ConfigTest.java
Labels: AwaitingReview.ReadyForMerge, feature.Timetable

#246 fix typo in UG
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
Labels: AwaitingReview.ReadyForMerge, feature.Timetable
